getwd()
install.packages("RColorBrewer")
install.packages("wordcloud")
install.packages("tm")
install.packages("SnowballC")
library("RColorBrewer")
library("wordcloud")
library("tm")
library("tmap")
library("SnowballC")

text <- readLines(file.choose())
docs <- Corpus(VectorSource(text))
docs <- tm_map(docs, tolower)
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, stem)
dts <- TermDocumentMatrix(docs)
m <- as.matrix(dts)
v <- sort(rowSums(m), decreasing = TRUE)
d <- data.frame(word = names(v),freq=v)
head(d,10)
wordcloud(d$word, freq=d$freq, min.freq=1, max.words=70, random.order=FALSE, rot.per=0.30, color=brewer.pal(8,"Dark2"))